mysql:
  zjly:
    host: 192.168.1.192
    port: 3306
    username: xjd
    password: NSaDKTGEeAqxox31OmD7hQzhQ1
    db_name: finance_router
api:
  api_flow:
    host: 192.168.1.192
    port: 13310
    username: zws_middleware_360
    password: maiS2ieb
    db_name: zws_middleware_360
tyh:
  tyh_api_flow:
    host: 192.168.1.192
    port: 13310
    username: tyh_cashloan
    password: 08*wP&DT@w#J
    db_name: tyh_cashloan

redis:
  zjly:
    host: 192.168.1.159
    port: 6379
    password: a6ENZ8CCM1xPhcf@
    db: 6
  api:
    host: 192.168.1.101
    port: 6379
    password: zQ6gmXuw0dodB@
    db: 9
