mysql:
  zjly:
    host: rm-wz965099vmp66lq0d.mysql.rds.aliyuncs.com
    port: 3306
    username: finace_router_sit
    password: V4T4BgYtZWlpFnSA
    db_name: finace_router_sit
api:
  api_flow:
    host: 192.168.1.192
    port: 13310
    username: zws_middleware_360
    password: maiS2ieb
    db_name: zws_middleware_360
tyh:
  tyh_api_flow:
    host: 192.168.1.192
    port: 13310
    username: tyh_cashloan
    password: 08*wP&DT@w#J
    db_name: tyh_cashloan
auto:
  auto_test:
    host: 192.168.2.20
    port: 3306
    username: root
    password: b2C@yQ8B2^U2AQXT3Evf
    db_name: automation_test_result

redis:
  zjly:
    host: 192.168.1.159
    port: 6379
    password: a6ENZ8CCM1xPhcf@
    db: 6
  api:
    host: 192.168.2.189
    port: 6379
    password: zhongli888
    db: 9
