funds_xxl_id:
  润楼中原: 877
  蒙苏商: 844
  哈密辽农: 822
  快乐通宝-蓝海: 806
  蓝海: 772
  HAMI_ZHONGBANG: 734
  步客长银: 705
  新长银: 659
  中原消金: 653
  长银宝付: 635
  蒙商: 623
  润楼: 617
  JMX: 611
  海峡: 607
  老长银: 591
  振兴V1: 587
  振兴: 583
  小米: 573
  裕民: 178